[package]
name = "telos-listener"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
telos-types = { workspace = true }
alloy = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
eyre = { workspace = true }
futures-util = { workspace = true }
