[package]
name = "telos-submitter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
telos-settler = { workspace = true }
alloy = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
eyre = { workspace = true }
