[package]
name = "telos-settler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
telos-types = { workspace = true }
telos-precompile = { workspace = true }
alloy = { workspace = true }
revm = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
eyre = { workspace = true }
