//! Solidity ABI bindings, generated by `alloy::sol!` at compile time.
//!
//! The macro expands the inline Solidity below into Rust types that
//! implement `SolEvent` (decode_log, SIGNATURE_HASH, etc.). Keeping the
//! interface in Solidity form — rather than hand-rolling Rust structs —
//! means the on-chain contract and the Rust types cannot drift.

use alloy::sol;

sol! {
    /// Emitted by the Tempo MPP contract when a payer commits to a payment intent.
    ///
    /// Three indexed topics is the EVM maximum; remaining fields land in `data`.
    #[derive(Debug)]
    event PaymentIntent(
        bytes32 indexed intentId,
        address indexed payer,
        address indexed merchant,
        address settlementAsset,
        uint256 settlementAmount,
        uint16 maxSlippageBps,
        uint64 deadline
    );

    /// Emitted by a Hyperliquid HyperEVM bridge or builder contract when a spot
    /// fill is reported back from L1. Fields use HL's native 1e8 fixed-point.
    /// `asset` is the EVM-side address of the spot token; the settler uses it
    /// to key its price book.
    #[derive(Debug)]
    event Fill(
        address indexed trader,
        bytes32 indexed orderId,
        address indexed asset,
        bool isBuy,
        uint64 priceE8,
        uint64 sizeE8,
        uint64 timestamp
    );
}

impl From<PaymentIntent> for telos_types::PaymentIntent {
    fn from(ev: PaymentIntent) -> Self {
        Self {
            intent_id: ev.intentId,
            payer: ev.payer,
            merchant: ev.merchant,
            settlement_asset: ev.settlementAsset,
            settlement_amount: ev.settlementAmount,
            max_slippage_bps: ev.maxSlippageBps,
            deadline: ev.deadline,
        }
    }
}

impl From<Fill> for telos_types::Fill {
    fn from(ev: Fill) -> Self {
        Self {
            trader: ev.trader,
            order_id: ev.orderId,
            asset: ev.asset,
            is_buy: ev.isBuy,
            price_e8: ev.priceE8,
            size_e8: ev.sizeE8,
            timestamp: ev.timestamp,
        }
    }
}
